Repository AJOUChakra7/ajou-ground, pull requests merged in 2023-03, with the labels that each got.

#5 Feat #1 : 프로젝트 세팅 - 모바일 뷰
  .prettierrc.json
  app/globals.css
  app/layout.js
  app/page.js
  app/page.module.css
  app/styles/global.css
  jsconfig.json
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: 🔧Chore

#4 데이터베이스 모델 구현
  lib/models/Ground.js
  lib/models/Reservation.js
  lib/models/User.js
  package-lock.json
  package.json
Labels: 🛠 Feat

#11 hotfix : 폴더 구조 변경
  app/layout.jsx
  app/login/page.jsx
  app/mypage/page.jsx
  app/page.jsx
  app/reservation/page.jsx
  components/Toast/index.jsx
  jsconfig.json
  styles/global.css
Labels: ⚡ Hotfix

#10 feat(reservation): 캘린더 추가
  app/reservation/page.jsx
  package-lock.json
  package.json
Labels: 🛠 Feat

#30 Feat #28 : 로그인 페이지 디자인 완성
  app/login/page.jsx
  public/ajouground.svg
  public/google.svg
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
Labels: 🛠 Feat

#24 Feat #9 : Toast component
  .eslintrc.json
  app/layout.jsx
  app/page.jsx
  components/Toast/index.jsx
  jsconfig.json
  package-lock.json
  package.json
  styles/config.js
  tailwind.config.js
Labels: 🛠 Feat

#27 Feat #25 : Footer
  app/page.jsx
  components/Footer/index.jsx
  tailwind.config.js
Labels: 🛠 Feat

#32 Feat #31 : 세팅 페이지 디자인 수정
  app/setting/page.jsx
Labels: 🛠 Feat

#43 Feat #40 : Modal Component 및 toast 추가
  app/layout.jsx
  app/page.jsx
  app/reservation/page.jsx
  components/ImgAndDesc/index.jsx
  components/Modal/index.jsx
  components/Modal/useModal.jsx
  components/MyHistoryDisplayCard/index.jsx
  components/MyReservationDisplayCard/index.jsx
  components/ReservationBtn/index.jsx
  components/Toast/index.jsx
  styles/global.css
  tailwind.config.js
Labels: 🛠 Feat

#47 Bug #45 : scroll view 수정 및 header 추가
  app/notice/page.jsx
  app/page.jsx
  app/reservation/[place]/page.jsx
  app/setting/page.jsx
  components/Footer/index.jsx
  components/Header/index.jsx
  styles/global.css
Labels: 🐛 Bug, ⚙Fix

#52 Bug #49 : 캘린더 선택 버그 해결
  app/reservation/[place]/page.jsx
  components/ReservationBtn/index.jsx
Labels: ⚙Fix
